name: nest-simulator-binder-environment
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - pip
  - nest

- pip:

    # To build and work with PyNEST
    - -r https://raw.githubusercontent.com/nest/nest-simulator/master/requirements_pynest.txt

    # To run NEST testsuite
    - -r https://raw.githubusercontent.com/nest/nest-simulator/master/requirements_testing.txt

    # To build NEST documentation
    - -r https://raw.githubusercontent.com/nest/nest-simulator/master/requirements_docs.txt

    # To run NEST Server
    - -r https://raw.githubusercontent.com/nest/nest-simulator/master/requirements_testing.txt
  