name: nest-simulator-binder-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - nest-simulator
  - numpy
  - pandas
  - python >= 3.10
  - pip:
    - elephant
    - viziphant
    - neo
    - PyNN