#
# get nest version from experimental ebrains
#
# env:
#   NEST_VERSION: $nest_version
#   EBRAINS_VERSION: "experimental"
#   EBRAINS_DISPLAY_NAME: "Experimental"
#
#
#checkout new branch this repo with nest version
#
#checkout nest-simulator
#
#copy files to new branch
#
#convert to notebooks
#
#name: Target Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Integration-with-Automation]

run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: ebrains-experimental
      DISPLAY_NAME: "EBRAINS-experimental"
    steps:
      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV

      - name: Use test variable
        run: |
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"

      - name: Get NEST version
        run: echo "NEST_VERSION=$(wget -q -O - 'https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/ebrains-spack-builds/-/raw/master/spack.yaml?ref_type=heads&inline=false' | sed -rn 's/^\s.*nest@([0-9]\.[0-9]).*/\1/p')" >> $GITHUB_ENV

      - name: Test environment variable
        run: |
          echo "The nest version in experimental is $NEST_VERSION"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git checkout -b 'nest$NEST_VERSION'

      - name: Run file copy action
        uses:
        with:
          source_repo: "jessica-mitchell/nest-simulator"
          source_path: "pynest/examples"
          destination_path: "footest"
          commit_message: "Test copy commit"
          create_pr: false
          source_repo_token: ${{ secrets.API_TOKEN_GITHUB }}
          destination_repo_token: ${{ secrets.API_TOKEN_GITHUB }}
