#
# get nest version from experimental ebrains
#
# env:
#   NEST_VERSION: $nest_version
#   EBRAINS_VERSION: "experimental"
#   EBRAINS_DISPLAY_NAME: "Experimental"
#
#
#checkout new branch this repo with nest version
#
#checkout nest-simulator
#
#copy files to new branch
#
#convert to notebooks
#
#name: Target Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Integration-with-Automation]

run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: ebrains-experimental
      DISPLAY_NAME: "EBRAINS-experimental"
    steps:
      - name: Get NEST version
        run: |
          wget -q -O spack.txt 'https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/ebrains-spack-builds/-/raw/master/spack.yaml?ref_type=heads&inline=false'
          ls
          sed -rn 's/^\s.*nest@([0-9]\.[0-9]).*/\1/p' spack.txt >> nestvers.txt
          cat nestvers.txt
          echo "NEST_VERSION = $(cat nestvers.txt)" >> $GITHUB_ENV

          #run: echo "NEST_VERSION = $(wget -q -O - 'https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/ebrains-spack-builds/-/raw/master/spack.yaml?ref_type=heads&inline=false' | sed -rn 's/^\s.*nest@([0-9]\.[0-9]).*/\1/p')" >> $GITHUB_ENV

      - name: Use environment variable
        run: |
          echo "The value of MY_ENV_VAR is $NEST_VERSION"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, NEST!
