name: testing pre-release workflow trigger!

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test-trigger]

run-name: ${{ github.actor }} is trying all the things

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      NAME: ebrains-experimental
      DISPLAY_NAME: "EBRAINS-experimental"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: echo "Setting up environment variables"
      - name: Create new branch
        run: |
          git checkout -B ${{ github.event.client_payload.tag }}
          git push -u origin ${{ github.event.client_payload.tag }}

      - name: Checkout nest-simulator repo
        uses: actions/checkout@v4
        with:
          repository: jessica-mitchell/dummy_repo
          # for testing use known branch
          # ref: refs/heads/jupytext
          ref: ${{ github.event.client_payload.tag }}  # Use the dynamically created branch
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: dummy_repo # Directory to place the repository in

      - name: Copy Python example files to current repo
        run: |
          # TODO ensure all necessary files are copied (consider non python files?)
          # for testing make temp directory
          mkdir temp_examples
          rsync -aP --exclude '**.png' --exclude '**.gif' dummy_repo/pynest/examples temp_examples
          # find nest-simulator/pynest/examples/ -iname "*.py" -exec cp --parents \{\} ./temp_examples \;

