name: testing pre-release workflow trigger!

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test-trigger]

run-name: ${{ github.actor }} is trying all the things

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      NAME: ebrains-experimental
      DISPLAY_NAME: "EBRAINS-experimental"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: echo "Setting up environment variables"
      - name: Create new branch
        run: |
          #git checkout -B ${{ github.event.client_payload.tag }}
          git checkout -B temp_branch

      - name: Checkout nest-simulator repo
        uses: actions/checkout@v4
        with:
          repository: jessica-mitchell/nest-simulator
          # for testing use known branch
          # ref: refs/heads/jupytext
          ref: master  # Use the dynamically created branch
          #ref: ${{ github.event.client_payload.tag }}  # Use the dynamically created branch
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: nest-simulator # Directory to place the repository in

      - name: Copy Python example files to current repo
        run: |
          # for testing make temp directory
          mkdir temp_examples
          rsync -aP --exclude '**.png' --exclude '**.gif' nest-simulator/pynest/examples temp_examples

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install ipykernel jupytext yq

      - name: "Convert to notebooks and set kernel"
        run: |
          cd temp_examples
          ls
          # Use yq to extract Python files and execute jupytext
          { yq -r '.directories[].convert2notebooks[]?' '../pynest_examples_metadata.yaml'
          } > convert.txt
          #> convert.txt
          while read line; do echo "$line" ; done <convert.txt
          # jupytext --to notebook "$file"
          exit 0
          # Use yq to extract Python files and execute jupytext
          # jupytext --to notebook "$file"
          # jupytext --to notebook  $(find temp_examples -iname "*.py")
          python -m ipykernel install --user --name "$NAME" --display-name "$DISPLAY_NAME"
          jupytext --set-kernel "$NAME"  $(find temp_examples -iname "*.ipynb")

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add temp_examples/
          git commit -m "Add Python files from nest ${{ github.event.client_payload.tag }}"
          git push origin HEAD
