name: testing metadata from yaml

on:
  workflow_dispatch:

run-name: ${{ github.actor }} is trying all the things

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: use metadata
        run: |
          YAML_FILE="pynest_examples_metadata.yaml"
          # Check if the YAML file exists
          if [ ! -f "$YAML_FILE" ]; then
            echo "YAML file not found: $YAML_FILE"
          exit 1
          fi

          # Use yq to extract Python files and execute jupytext
          yq -r '.directories[].conver2notebooks[]?' "$YAML_FILE" > convert.txt
          while read line; do echo "$line" ; done <convert.txt
          # jupytext --to notebook "$file"
