name: testing metadata from yaml

on:
  workflow_dispatch:

run-name: ${{ github.actor }} is trying all the things

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install ipykernel jupytext yq
      - name: use metadata
        run: |
          # Use yq to extract Python files and execute jupytext
          yq -r '.directories[].conver2notebooks[]?' 'pynest_examples_metadata.yaml' > convert.txt
          cat convert.txt
          #> convert.txt
          #while read line; do echo "$line" ; done <convert.txt
          # jupytext --to notebook "$file"
